package export

import (
	"fmt"
	"io"
	"time"

	"github.com/drakeafk/cmdsetgo/internal/pick"
	"github.com/drakeafk/cmdsetgo/internal/redact"
)

// BashExporter generates a strict-mode bash script.
func BashExporter(w io.Writer, selection pick.Selection, redactRegex []string) error {
	fmt.Fprintln(w, "#!/usr/bin/env bash")
	fmt.Fprintln(w, "set -euo pipefail")
	fmt.Fprintf(w, "# Generated by cmdsetgo at %s\n", time.Now().Format(time.RFC1123))
	fmt.Fprintf(w, "# Scope: %s\n", selection.Scope)
	if selection.RepoRoot != "" {
		fmt.Fprintf(w, "# Repo: %s\n", selection.RepoRoot)
	}
	fmt.Fprintln(w)

	currentCwd := ""
	for _, ev := range selection.Items {
		// Insert CD if needed
		if ev.Cwd != currentCwd {
			// Redact CWD if it might contain secrets (though usually paths are fine)
			fmt.Fprintf(w, "cd \"%s\"\n", ev.Cwd)
			currentCwd = ev.Cwd
		}

		cmdRedacted := redact.Redact(ev.Cmd, redactRegex)
		fmt.Fprintf(w, "# %s\n", ev.Ts.Format(time.RFC3339))
		fmt.Fprintln(w, cmdRedacted)
	}

	return nil
}
